import { AppShell } from "@/components/shell";
import { ClaimStatusControl, CopyButton } from "@/components/interactions";
import { Badge, Code, DataState, Panel, PanelHeader, Progress, type Status } from "@/components/ui";
import { load, provena } from "@/lib/provena/server";
import { formatDate, payloadText } from "@/lib/provena/view-models";
import { AlertTriangle, CheckCircle2, CircleDot, LockKeyhole, ShieldAlert } from "lucide-react";

export const metadata = { title: "Explain claim" };
export const dynamic = "force-dynamic";

export default async function ClaimPage({ params }: { params: Promise<{ claimId: string }> }) {
  const { claimId } = await params;
  const result = await load(() => provena.explain(claimId));
  if (result.data === null) return <AppShell active="/memories"><div className="content"><DataState title="Claim explanation could not be loaded" message={result.error} tone="danger" /></div></AppShell>;
  const data = result.data;
  const claim = data.claim;
  const authority = data.evidence.map((item) => item.event.authority).sort((a, b) => ["ephemeral", "low", "medium", "high"].indexOf(b) - ["ephemeral", "low", "medium", "high"].indexOf(a))[0] ?? "unavailable";
  const extractionFact = data.extractions.flatMap((run) => run.facts).find((fact) => String(fact.claim_id) === claim.id);
  const confidence = typeof extractionFact?.confidence === "number" ? Math.round(extractionFact.confidence * 100) : null;
  const title = `${claim.subject}.${claim.predicate}`;
  const transitions: Partial<Record<Status, Array<{ status: Status; label: string }>>> = {
    candidate: [{ status: "active", label: "Activate" }, { status: "quarantined", label: "Quarantine" }, { status: "deleted", label: "Reject" }],
    active: [{ status: "verified", label: "Verify" }, { status: "quarantined", label: "Quarantine" }, { status: "expired", label: "Expire" }, { status: "deleted", label: "Delete" }],
    verified: [{ status: "quarantined", label: "Quarantine" }, { status: "expired", label: "Expire" }, { status: "deleted", label: "Delete" }],
    conflicted: [{ status: "active", label: "Activate" }, { status: "verified", label: "Verify" }, { status: "quarantined", label: "Quarantine" }, { status: "deleted", label: "Delete" }],
    quarantined: [{ status: "candidate", label: "Return to review" }, { status: "deleted", label: "Delete" }],
    ephemeral: [{ status: "candidate", label: "Return to review" }, { status: "expired", label: "Expire" }, { status: "deleted", label: "Delete" }],
    expired: [{ status: "active", label: "Reactivate" }, { status: "deleted", label: "Delete" }],
    superseded: [{ status: "active", label: "Reactivate" }, { status: "deleted", label: "Delete" }],
    deleted: [{ status: "candidate", label: "Restore to review" }],
  };
  return <AppShell active="/memories" scopeId={claim.scope_id}><div className="content explain-page">
    <div className="security-strip"><ShieldAlert size={14}/><span><b>Security Notice:</b> Memory authority does not authorize an agent action. Evidence payloads are rendered as untrusted text.</span><Code>POLICY-SEC-09</Code></div>
    <div className="claim-hero"><div><div className="cluster breadcrumbs"><Code>scope: {claim.scope_id}</Code><Badge tone={claim.status as Status}>{claim.status}</Badge><Badge tone={authority === "high" ? "high" : authority === "low" ? "low" : "neutral"}>Authority: {authority}</Badge>{confidence !== null && <Badge>Confidence: {confidence}%</Badge>}</div><h1>{title}</h1><p className="mono-small">Recorded: {formatDate(claim.recorded_at)} · Valid: [{claim.valid_from ? formatDate(claim.valid_from) : "unspecified"} → {claim.valid_to ? formatDate(claim.valid_to) : "open-ended"}]</p></div><div><div className="cluster claim-id"><Code>id: {claim.id}</Code><CopyButton compact label="Copy claim JSON" value={JSON.stringify(data, null, 2)}/></div><ClaimStatusControl claimId={claim.id} transitions={transitions[claim.status as Status] ?? []}/></div></div>
    <div className="explain-top">
      <Panel><PanelHeader title="SECTION A: WHAT PROVENA BELIEVES" actions={<Code>status v{claim.status_version}</Code>}/><div className="panel-body stack"><div className="statement"><span className="eyebrow">Scoped proposition</span><strong>{title}</strong><small>Stored claim proposition</small></div><div><span className="eyebrow">Deconstructed semantic triple</span><div className="triple"><Code>sub: {claim.subject}</Code><span>→</span><Code>pred: {claim.predicate}</Code><span>→</span><Code>object: JSON</Code></div></div><div><span className="eyebrow">Formal structured proposition</span><pre className="code-block">{JSON.stringify({ subject: claim.subject, predicate: claim.predicate, value: claim.value }, null, 2)}</pre></div><div className="grid-2"><div className="kv"><label>Mutability</label><code>Append-only history</code></div><div className="kv"><label>Storage engine</label><code>PostgreSQL</code></div></div></div></Panel>
      <Panel><PanelHeader title="SECTION B: WHY PROVENA BELIEVES IT" actions={<Badge>{data.evidence.length + data.extractions.length + data.actions.length} Recorded Stages</Badge>}/><div className="panel-body"><p className="small muted">Recorded lineage from immutable evidence through extraction and claim-state actions.</p><div className="stage-list">{data.evidence.map((item, index)=><div className="stage" key={item.id}><span>{String(index + 1).padStart(2,"0")}</span><div><b>{item.event.source_kind} event</b><small>{item.event.id} · authority {item.event.authority}</small></div><time>{formatDate(item.event.recorded_at)}</time></div>)}{data.extractions.map((run, index)=><div className="stage" key={run.id}><span>{String(data.evidence.length + index + 1).padStart(2,"0")}</span><div><b>Extraction run: {run.status}</b><small>{run.extractor_model} · {run.embedding_model}</small></div><time>{formatDate(run.created_at)}</time></div>)}{data.actions.map((action, index)=><div className={index === data.actions.length - 1 ? "stage stage-current" : "stage"} key={`${action.action}-${action.created_at}`}><span>{String(data.evidence.length + data.extractions.length + index + 1).padStart(2,"0")}</span><div><b>{action.action}</b><small>{action.reason}</small></div><time>{formatDate(action.created_at)}</time></div>)}</div></div></Panel>
    </div>
    <Panel><PanelHeader title="SECTION C: ORIGINAL EVIDENCE & UNTRUSTED SOURCE EVENTS" actions={<Badge tone="conflicted">Untrusted source payload</Badge>}/><div className="panel-body stack">{data.evidence.length ? data.evidence.map(({ id, event })=><div className="evidence-quote" key={id}><span className="eyebrow">{event.source_kind} · authority {event.authority}</span><p>{payloadText(event.payload)}</p><div className="kv-grid evidence-kv"><div className="kv"><label>Event ID</label><code>{event.id}</code></div><div className="kv"><label>Actor reference</label><code>{event.actor_ref ?? "Unavailable"}</code></div><div className="kv"><label>Credential</label><code>{event.credential ? `${event.credential.label} (${event.credential.role})` : "Unavailable"}</code></div><div className="kv"><label>Recorded</label><code>{formatDate(event.recorded_at)}</code></div></div></div>) : <DataState title="No evidence returned" message="A claim without evidence violates Provena's storage invariant; inspect the API and database." tone="danger"/>}</div></Panel>
    <Panel><PanelHeader title="SECTION D: EXTRACTION & EMBEDDING TELEMETRY" actions={<Badge tone={data.extractions.some(run=>run.status === "failed") ? "conflicted" : "verified"}>{data.extractions.length ? "Recorded runs" : "Manual claim"}</Badge>}/><div className="panel-body telemetry-grid">{data.extractions.length ? data.extractions.map(run=><div className="kv" key={run.id}><label>{run.status} extraction</label><strong>{run.extractor_model}</strong><p>{run.embedding_model} · {formatDate(run.created_at)}</p>{run.error && <p className="text-conflicted">{run.error}</p>}</div>) : <div className="kv"><label>Extraction</label><strong>Not recorded</strong><p>This claim may have been submitted manually.</p></div>}{confidence !== null && <div className="kv"><label>Extraction confidence</label><strong>{confidence}%</strong><Progress value={confidence}/></div>}</div></Panel>
    <Panel><PanelHeader title="SECTION E: RELATIONSHIPS & KNOWLEDGE GRAPH CONNECTIONS"/><div className="relationship-list">{data.relationships.length ? data.relationships.map(relation=><div className={relation.kind === "related_to" ? "relation-warn" : ""} key={relation.id}><b>{relation.kind}</b>{relation.kind === "related_to" ? <AlertTriangle size={14}/> : <CheckCircle2 size={14}/>}<span><Code>{relation.from_claim_id}</Code> → <Code>{relation.to_claim_id}</Code> · {relation.reason}</span><Badge>{relation.kind}</Badge></div>) : <div><b>NO RELATIONSHIPS</b><CheckCircle2 size={14}/><span>No recorded graph relationships in this organization.</span><Badge tone="verified">Clean</Badge></div>}</div></Panel>
    <Panel><PanelHeader title="SECTION F: AGENT RETRIEVAL HISTORY" actions={<Badge>{data.retrievals.length} Events Recorded</Badge>}/><div className="table-wrap"><table className="data-table retrieval-history"><thead><tr><th>Retrieval ID</th><th>Timestamp</th><th>Influence attribution</th></tr></thead><tbody>{data.retrievals.map(item=><tr key={item.id}><td><Code>{item.id}</Code></td><td>{formatDate(item.created_at)}</td><td>{data.action_influence}</td></tr>)}</tbody></table>{!data.retrievals.length && <DataState title="No retrieval history" message="This claim has not been returned by an audited agent retrieval."/>}</div></Panel>
    <Panel><PanelHeader title="SECTION G: IMMUTABLE APPEND-ONLY LEDGER TRAIL" actions={<span className="mono-small">{data.actions.length} actions</span>}/><div className="ledger-timeline">{data.actions.map((action,index)=><div className={index===data.actions.length-1?"timeline-current":""} key={`${action.action}-${action.created_at}`}><span className="timeline-dot">{index===data.actions.length-1?<LockKeyhole size={14}/>:<CircleDot size={14}/>}</span><div><b>{formatDate(action.created_at)} · {action.action}</b><p>{action.reason} · {action.actor_ref}</p></div><Code>{action.new_status ?? action.old_status ?? "recorded"}</Code></div>)}</div></Panel>
  </div></AppShell>;
}
