"""initial evidence model

Revision ID: ccc08f8f4372
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ccc08f8f4372'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('scope',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'organization' AND parent_id IS NULL AND project_id IS NULL) OR (kind <> 'organization' AND parent_id IS NOT NULL AND project_id IS NOT NULL)", name='scope_shape'),
    sa.CheckConstraint("kind IN ('organization','project','branch')", name='scope_kind'),
    sa.ForeignKeyConstraint(['organization_id', 'parent_id'], ['scope.organization_id', 'scope.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['project.organization_id', 'project.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('organization_id', 'parent_id', 'kind', 'key')
    )
    op.create_index('uq_org_root_scope', 'scope', ['organization_id'], unique=True, postgresql_where=sa.text("kind = 'organization'"))
    op.create_index('uq_project_scope', 'scope', ['organization_id', 'project_id'], unique=True, postgresql_where=sa.text("kind = 'project'"))
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('candidate','active','verified','conflicted','superseded','quarantined','expired','ephemeral','deleted')", name='claim_status'),
    sa.CheckConstraint('status_version >= 0', name='claim_status_version'),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_from < valid_to', name='claim_valid_interval'),
    sa.ForeignKeyConstraint(['organization_id', 'scope_id'], ['scope.organization_id', 'scope.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_index('ix_claim_lookup', 'claim', ['organization_id', 'scope_id', 'subject', 'predicate'], unique=False)
    op.create_table('retrieval_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=True),
    sa.Column('actor_ref', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'scope_id'], ['scope.organization_id', 'scope.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'agent_id'], ['agent.organization_id', 'agent.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'scope_id'], ['scope.organization_id', 'scope.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_table('claim_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('from_claim_id', sa.UUID(), nullable=False),
    sa.Column('to_claim_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('supports','contradicts','supersedes','derived_from','related_to')", name='relationship_kind'),
    sa.CheckConstraint('from_claim_id <> to_claim_id', name='relationship_distinct'),
    sa.ForeignKeyConstraint(['organization_id', 'from_claim_id'], ['claim.organization_id', 'claim.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'to_claim_id'], ['claim.organization_id', 'claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'from_claim_id', 'to_claim_id', 'kind')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('authority', sa.String(length=16), nullable=False),
    sa.Column('actor_ref', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_kind IN ('user_statement','assistant_inference') AND authority='low') OR (source_kind='hypothesis' AND authority='ephemeral')", name='event_authority_policy'),
    sa.CheckConstraint("source_kind IN ('user_statement','assistant_inference','hypothesis')", name='event_source_kind'),
    sa.ForeignKeyConstraint(['organization_id', 'scope_id'], ['scope.organization_id', 'scope.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'session_id'], ['session.organization_id', 'session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_table('memory_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_ref', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'claim_id'], ['claim.organization_id', 'claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'claim_id', 'version')
    )
    op.create_table('retrieval_item',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('retrieval_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'claim_id'], ['claim.organization_id', 'claim.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'retrieval_id'], ['retrieval_event.organization_id', 'retrieval_event.id'], ),
    sa.PrimaryKeyConstraint('retrieval_id', 'claim_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'claim_id'], ['claim.organization_id', 'claim.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'event_id'], ['event.organization_id', 'event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'claim_id', 'event_id')
    )
    op.execute("""
    CREATE FUNCTION provena_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END $$;
    """)
    for table in ('scope', 'event', 'evidence', 'memory_action', 'claim_relationship', 'retrieval_event', 'retrieval_item'):
        op.execute(f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION provena_append_only()")
    op.execute("""
    CREATE FUNCTION provena_claim_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'claims cannot be deleted'; END IF;
      IF ROW(NEW.organization_id,NEW.scope_id,NEW.subject,NEW.predicate,NEW.value,NEW.valid_from,NEW.valid_to,NEW.recorded_at)
         IS DISTINCT FROM ROW(OLD.organization_id,OLD.scope_id,OLD.subject,OLD.predicate,OLD.value,OLD.valid_from,OLD.valid_to,OLD.recorded_at)
      THEN RAISE EXCEPTION 'claim proposition is immutable'; END IF;
      IF NEW.status_version <> OLD.status_version + 1 OR NEW.status IS NOT DISTINCT FROM OLD.status OR NOT EXISTS (
        SELECT 1 FROM memory_action a WHERE a.organization_id = OLD.organization_id
          AND a.claim_id = OLD.id AND a.version = NEW.status_version
          AND a.old_status = OLD.status AND a.new_status = NEW.status
      ) THEN RAISE EXCEPTION 'status change requires a matching memory action'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER claim_guard BEFORE UPDATE OR DELETE ON claim FOR EACH ROW EXECUTE FUNCTION provena_claim_guard();
    """)
    op.execute("""
    CREATE FUNCTION provena_claim_has_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM evidence WHERE organization_id = NEW.organization_id AND claim_id = NEW.id)
      THEN RAISE EXCEPTION 'claim requires evidence'; END IF;
      RETURN NULL;
    END $$;
    CREATE CONSTRAINT TRIGGER claim_has_evidence AFTER INSERT ON claim DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION provena_claim_has_evidence();
    """)
    op.execute("""
    CREATE FUNCTION provena_evidence_scope() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS (SELECT 1 FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.claim_id)
         AND EXISTS (SELECT 1 FROM event WHERE organization_id=NEW.organization_id AND id=NEW.event_id)
         AND (SELECT scope_id FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.claim_id)
         IS DISTINCT FROM (SELECT scope_id FROM event WHERE organization_id=NEW.organization_id AND id=NEW.event_id)
      THEN RAISE EXCEPTION 'evidence and claim scope differ'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER evidence_scope BEFORE INSERT ON evidence FOR EACH ROW EXECUTE FUNCTION provena_evidence_scope();
    """)
    op.execute("""
    CREATE FUNCTION provena_scope_parent() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE parent_kind text; parent_project uuid;
    BEGIN
      IF NEW.kind='organization' THEN RETURN NEW; END IF;
      SELECT kind, project_id INTO parent_kind, parent_project FROM scope
        WHERE organization_id=NEW.organization_id AND id=NEW.parent_id;
      IF (NEW.kind='project' AND parent_kind IS DISTINCT FROM 'organization') OR
         (NEW.kind='branch' AND (parent_kind IS DISTINCT FROM 'project' OR parent_project IS DISTINCT FROM NEW.project_id))
      THEN RAISE EXCEPTION 'invalid scope parent'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER scope_parent BEFORE INSERT OR UPDATE ON scope FOR EACH ROW EXECUTE FUNCTION provena_scope_parent();
    """)
    op.execute("""
    CREATE FUNCTION provena_session_scope() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.session_id IS NOT NULL AND NEW.scope_id IS DISTINCT FROM
         (SELECT scope_id FROM session WHERE organization_id=NEW.organization_id AND id=NEW.session_id)
      THEN RAISE EXCEPTION 'event and session scope differ'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER event_session_scope BEFORE INSERT ON event FOR EACH ROW EXECUTE FUNCTION provena_session_scope();
    """)
    op.execute("""
    CREATE FUNCTION provena_relationship_scope() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS (SELECT 1 FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.from_claim_id)
         AND EXISTS (SELECT 1 FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.to_claim_id)
         AND (SELECT scope_id FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.from_claim_id)
         IS DISTINCT FROM (SELECT scope_id FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.to_claim_id)
      THEN RAISE EXCEPTION 'relationship claims must share a scope'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER relationship_scope BEFORE INSERT ON claim_relationship FOR EACH ROW EXECUTE FUNCTION provena_relationship_scope();
    """)
    op.execute("""
    CREATE FUNCTION provena_retrieval_scope() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS (SELECT 1 FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.claim_id)
         AND EXISTS (SELECT 1 FROM retrieval_event WHERE organization_id=NEW.organization_id AND id=NEW.retrieval_id)
         AND (SELECT scope_id FROM claim WHERE organization_id=NEW.organization_id AND id=NEW.claim_id)
         IS DISTINCT FROM (SELECT scope_id FROM retrieval_event WHERE organization_id=NEW.organization_id AND id=NEW.retrieval_id)
      THEN RAISE EXCEPTION 'retrieval claim must share request scope'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER retrieval_scope BEFORE INSERT ON retrieval_item FOR EACH ROW EXECUTE FUNCTION provena_retrieval_scope();
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    op.execute('DROP FUNCTION provena_retrieval_scope() CASCADE')
    op.execute('DROP FUNCTION provena_relationship_scope() CASCADE')
    op.execute('DROP FUNCTION provena_session_scope() CASCADE')
    op.execute('DROP FUNCTION provena_scope_parent() CASCADE')
    op.execute('DROP FUNCTION provena_evidence_scope() CASCADE')
    op.execute('DROP FUNCTION provena_claim_has_evidence() CASCADE')
    op.execute('DROP FUNCTION provena_claim_guard() CASCADE')
    op.execute('DROP FUNCTION provena_append_only() CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('retrieval_item')
    op.drop_table('memory_action')
    op.drop_table('event')
    op.drop_table('claim_relationship')
    op.drop_table('session')
    op.drop_table('retrieval_event')
    op.drop_index('ix_claim_lookup', table_name='claim')
    op.drop_table('claim')
    op.drop_index('uq_org_root_scope', table_name='scope', postgresql_where=sa.text("kind = 'organization'"))
    op.drop_index('uq_project_scope', table_name='scope', postgresql_where=sa.text("kind = 'project'"))
    op.drop_table('scope')
    op.drop_table('project')
    op.drop_table('agent')
    op.drop_table('organization')
    # ### end Alembic commands ###
